In [0]:
#downgrading the version of numpy

!pip install numpy==1.16.2
import numpy as np
print(np.__version__)

1.16.2


In [0]:
from keras.datasets import imdb

Using TensorFlow backend.


In [0]:
vocab_size = 10000

In [0]:
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size)

In [0]:
from keras.preprocessing.sequence import pad_sequences
vocab_size = 10000 #vocab size
maxlen = 300

In [0]:
#load dataset as a list of ints
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size)
#make all sequences of the same length
x_train = pad_sequences(x_train, maxlen=maxlen)
x_test =  pad_sequences(x_test, maxlen=maxlen)
#y_train = pad_sequences(y_train, maxlen=maxlen)

In [0]:
x_train

array([[   0,    0,    0, ...,   19,  178,   32],
       [   0,    0,    0, ...,   16,  145,   95],
       [   0,    0,    0, ...,    7,  129,  113],
       ...,
       [   0,    0,    0, ...,    4, 3586,    2],
       [   0,    0,    0, ...,   12,    9,   23],
       [   0,    0,    0, ...,  204,  131,    9]], dtype=int32)

In [11]:
#Creating the word index

word_to_index = imdb.get_word_index()
for (k,v) in word_to_index.items():
  word_to_index[k] = v + 3

index_to_word = {}
index_to_word[0] = "PAD"
index_to_word[1] = "START"
index_to_word[2] = "OOV"
for (k,v) in word_to_index.items():
  index_to_word[v] = k
for r in range(len(x_train)):
  for c in range(len(x_train[r])):
    idx=x_train[r][c]
    wrd=index_to_word[idx]
    print(wrd)
  print(" -> %d" % y_train[r])
print("\n")

Output hidden; open in https://colab.research.google.com to view.

In [1]:
from keras.preprocessing.text import Tokenizer
from keras.models import Sequential, load_model
from keras.layers import LSTM, Dense, Dropout, Embedding, Masking, Bidirectional
from keras.optimizers import Adam
from keras import backend
from keras.callbacks import EarlyStopping, ModelCheckpoint, TensorBoard, ReduceLROnPlateau


Using TensorFlow backend.


In [0]:
model = Sequential()

In [4]:
# Embedding layer
model.add(
    Embedding(
        input_dim=1000,
        output_dim=100,
        weights=None,
        trainable=True))

Instructions for updating:
Colocations handled automatically by placer.


In [5]:
# Recurrent layer
model.add(
    LSTM(
        64, return_sequences=False, dropout=0.1,
        recurrent_dropout=0.1))

# Fully connected layer
model.add(Dense(64, activation='sigmoid'))

# Dropout for regularization
model.add(Dropout(0.5))

# Output layer
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(
    optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, None, 100)         100000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 64)                42240     
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160      
_________________________________________________________________
dropout_1 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 65        
Total params: 146,465
Trainable params: 146,465
Non-trainable params: 0
_________________________________________________________________


In [0]:
callback_reduce_lr = ReduceLROnPlateau(monitor='acc',
                                      factor=0.1,
                                      min_lr=1e-4,
                                      patience=0,
                                      verbose=2)

In [0]:
SEQUENCES = 50
TIME_STEPS = 100

In [0]:
import numpy as np

In [0]:
x_train = np.random.randint(1000, size=(SEQUENCES, TIME_STEPS), dtype='int32')


In [10]:
x_train

array([[717, 693, 335, ..., 478, 346, 394],
       [ 28, 365, 999, ...,  41, 869, 748],
       [259, 537, 782, ..., 628, 133, 850],
       ...,
       [ 92, 413, 205, ..., 671,   9,  43],
       [707, 437, 176, ..., 431, 161, 335],
       [836, 334, 855, ..., 103, 382, 290]], dtype=int32)

In [0]:
y_train = np.random.rand(SEQUENCES)


In [12]:
y_train

array([0.51933547, 0.55961737, 0.20640753, 0.06456199, 0.86201601,
       0.99652067, 0.10942667, 0.67107205, 0.25507454, 0.49564084,
       0.84486618, 0.70661871, 0.85961904, 0.1908622 , 0.07331188,
       0.64560822, 0.57456262, 0.55627679, 0.47128716, 0.13057269,
       0.48451227, 0.32222298, 0.49125188, 0.51632376, 0.04055604,
       0.17091777, 0.30316692, 0.38249272, 0.75941786, 0.39420872,
       0.17585364, 0.20250204, 0.74356043, 0.69476621, 0.41442995,
       0.2785762 , 0.55997127, 0.32285356, 0.87732838, 0.98392715,
       0.73859457, 0.52034872, 0.3021919 , 0.87060276, 0.05473246,
       0.58066499, 0.94885231, 0.33671194, 0.84915402, 0.65360319])

In [13]:
intialmodel = model.fit(x_train, y_train, epochs = 500, batch_size = 50,verbose=1,callbacks=[callback_reduce_lr]) 


Instructions for updating:
Use tf.cast instead.
Epoch 1/500
50/50 [==============================] - 3s 69ms/step - loss: 0.7157 - acc: 0.0000e+00
Epoch 2/500
50/50 [==============================] - 0s 4ms/step - loss: 0.7292 - acc: 0.0000e+00

Epoch 00002: ReduceLROnPlateau reducing learning rate to 0.00010000000475.
Epoch 3/500
50/50 [==============================] - 0s 3ms/step - loss: 0.7261 - acc: 0.0000e+00

Epoch 00003: ReduceLROnPlateau reducing learning rate to 0.0001.
Epoch 4/500
50/50 [==============================] - 0s 3ms/step - loss: 0.8074 - acc: 0.0000e+00
Epoch 5/500
50/50 [==============================] - 0s 3ms/step - loss: 0.7474 - acc: 0.0000e+00
Epoch 6/500
50/50 [==============================] - 0s 3ms/step - loss: 0.7356 - acc: 0.0000e+00
Epoch 7/500
50/50 [==============================] - 0s 3ms/step - loss: 0.7648 - acc: 0.0000e+00
Epoch 8/500
50/50 [==============================] - 0s 3ms/step - loss: 0.7475 - acc: 0.0000e+00
Epoch 9/500
50/50 [======

In [14]:
from google.colab import drive
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive/


In [0]:
#Save the model
model.save('/content/drive/My Drive/.h5')

In [0]:
model = load_model('/content/drive/My Drive/.h5')

In [18]:
model.fit(x_train, y_train, batch_size=50, epochs=500)

Epoch 1/500
50/50 [==============================] - 1s 15ms/step - loss: 0.5572 - acc: 0.0000e+00
Epoch 2/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5616 - acc: 0.0000e+00
Epoch 3/500
50/50 [==============================] - 0s 4ms/step - loss: 0.5720 - acc: 0.0000e+00
Epoch 4/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5663 - acc: 0.0000e+00
Epoch 5/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5802 - acc: 0.0000e+00
Epoch 6/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5754 - acc: 0.0000e+00
Epoch 7/500
50/50 [==============================] - 0s 4ms/step - loss: 0.5640 - acc: 0.0000e+00
Epoch 8/500
50/50 [==============================] - 0s 4ms/step - loss: 0.5764 - acc: 0.0000e+00
Epoch 9/500
50/50 [==============================] - 0s 4ms/step - loss: 0.5733 - acc: 0.0000e+00
Epoch 10/500
50/50 [==============================] - 0s 3ms/step - loss: 0.5572 - acc: 0.0000e+00
Epoch 11/500
50/50

In [22]:
print(model.evaluate(x_train, y_train, batch_size = 50))
print('\nModel Performance: Log Loss and Accuracy on validation data')
print(model.evaluate(x_test, y_test, batch_size = 50))

50/50 [==============================] - 0s 918us/step
[0.5260888934135437, 0.0]

Model Performance: Log Loss and Accuracy on validation data


NameError: ignored